(() => {
  'use strict';
  const esc = value => String(value ?? '').normalize('NFC').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const number = value => value==null?'—':Number(value).toLocaleString('vi-VN',{maximumFractionDigits:1});
  const elapsed = value => {
    const seconds=Math.max(0,Math.floor(Number(value||0)/1000));
    return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
  };
  const initials = name => String(name||'').trim().split(/\s+/).slice(-2).map(word=>word[0]||'').join('').toLocaleUpperCase('vi-VN');
  let current=null;
  const dialogs=new Map();
  function dialog(key,title,content,wide=false) {
    let node=dialogs.get(key);
    if(!node) {
      node=document.createElement('dialog');node.className=wide?'leaderboard-dialog course-dialog':'top-participant-dialog course-detail-dialog';
      document.body.appendChild(node);dialogs.set(key,node);
    }
    node.innerHTML=`<header class="presentation-head"><div><span>GIA LAI · TỔNG KẾT KHÓA</span><h2>${esc(title)}</h2></div><button class="presentation-close" type="button" data-close>Đóng ×</button></header><div class="${wide?'leaderboard-dialog-content':'course-detail-content'}">${content}</div>`;
    node.querySelector('[data-close]').onclick=()=>node.close();
    const shown=current;
    node.querySelectorAll('[data-unit]').forEach(button=>button.onclick=()=>openUnit(Number(button.dataset.unit),shown));
    node.querySelectorAll('[data-individual]').forEach(button=>button.onclick=()=>openPerson(shown?.individualTop?.[Number(button.dataset.individual)]));
    if(!node.open)node.showModal();return node;
  }
  function medal(rank) {
    const leaf='<path d="M27 57 C12 43 11 27 19 9" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M22 53 C12 55 8 48 9 42 C17 43 22 47 22 53 M17 42 C8 43 5 36 7 30 C14 31 18 36 17 42 M15 31 C7 29 6 21 9 17 C15 20 17 26 15 31 M17 20 C11 16 13 8 18 4 C22 10 21 16 17 20 M24 48 C30 43 28 36 24 33 C20 39 20 44 24 48 M20 35 C26 30 25 24 21 20 C17 25 17 31 20 35"/>';
    return `<span class="podium-medal"><svg viewBox="0 0 100 70" aria-hidden="true"><g fill="currentColor">${leaf}<g transform="translate(100 0) scale(-1 1)">${leaf}</g></g><circle cx="50" cy="29" r="24" fill="currentColor"/><text x="50" y="39" text-anchor="middle" fill="white" font-family="Georgia,serif" font-size="32">${rank}</text></svg></span>`;
  }
  function cards(data) {
    const card=(unit,index,featured)=>`<button type="button" class="top-participant-card ${featured?'podium-card course-podium-card':'ranking-card course-ranking-card'} rank-${unit.rank}" data-unit="${index}" aria-label="Xem chi tiết ${esc(unit.unit)}">${featured?medal(unit.rank):`<span class="rank-badge">#${unit.rank}</span>`}<span class="course-unit-name">${esc(unit.unit)}</span><span class="course-total">${number(unit.total)}<small>/100</small></span><span class="course-card-metrics"><span>Thành tích <b>${number(unit.achievement)}</b></span><span>Lượt tham gia <b>${unit.accepted}</b></span></span><span class="course-card-coverage">Có bài ở ${unit.covered}/${unit.totalSessions} phiên</span><span class="podium-cta">Xem chi tiết <b>→</b></span></button>`;
    return `<div class="top-podium" data-count="${Math.min(3,data.top.length)}">${data.top.slice(0,3).map((unit,index)=>card(unit,index,true)).join('')}</div>${data.top.length>3?`<div class="course-runners">${data.top.slice(3).map((unit,index)=>card(unit,index+3,false)).join('')}</div>`:''}`;
  }
  function individualCards(data) {
    const people=data.individualTop||[];
    const card=(person,index,featured)=>`<button type="button" class="top-participant-card ${featured?'podium-card course-individual-podium':'ranking-card course-individual-ranking'} rank-${person.rank}" data-individual="${index}" aria-label="Xem bài làm toàn khóa của ${esc(person.name)}">${featured?medal(person.rank):`<span class="rank-badge">#${person.rank}</span>`}<span class="${featured?'podium-identity':'ranking-identity'}">${featured?`<span class="podium-avatar">${esc(initials(person.name))}</span>`:''}<span class="participant-info"><strong class="participant-name">${esc(person.name)}</strong><span class="participant-unit">${esc(person.unit)}</span></span></span><span class="course-individual-score"><strong>${number(person.achievement)}<small>/100</small></strong><span>Điểm toàn khóa</span></span><span class="course-individual-meta"><span><b>${person.covered}/${person.totalSessions}</b> phiên có bài</span><span><b>${elapsed(person.elapsedMs)}</b> tổng thời gian nộp</span></span><span class="podium-cta">Xem bài làm <b>→</b></span></button>`;
    return `<div class="top-podium" data-count="${Math.min(3,people.length)}">${people.slice(0,3).map((person,index)=>card(person,index,true)).join('')}</div>${people.length>3?`<div class="course-runners">${people.slice(3).map((person,index)=>card(person,index+3,false)).join('')}</div>`:''}`;
  }
  function openUnit(index,shown=current) {
    const unit=shown?.top[index];if(!unit)return;
    const node=dialog('unit',unit.unit,`<div class="course-detail-metrics"><strong>Điểm tổng ${number(unit.total)}/100</strong><span>Thành tích ${number(unit.achievement)}/100</span><span>Điểm tham gia ${number(unit.participation)}/100</span></div><div class="course-score-breakdown"><span><strong>${number(unit.achievement)} × 85%</strong><b>${number(unit.achievement*.85)} điểm</b><small>Thành tích · tối đa 85 điểm</small></span><span class="course-score-plus" aria-hidden="true">+</span><span><strong>${number(unit.participation)} × 15%</strong><b>${number(unit.participation*.15)} điểm</b><small>Tham gia · tối đa 15 điểm</small></span></div><p>${unit.uniqueParticipants} người tham gia · ${unit.accepted} lượt người–phiên hợp lệ</p><h3>Kết quả từng phiên</h3><div class="course-table-wrap"><table class="course-table"><thead><tr><th>Phiên</th><th>Người tham gia không trùng</th><th>Điểm trung bình /100</th></tr></thead><tbody>${unit.sessions.map(session=>`<tr><td>Phiên ${session.id}</td><td>${session.participants}</td><td>${number(session.average)}</td></tr>`).join('')}</tbody></table></div><h3>Học viên có bài được tính</h3><div class="course-people">${unit.people.map((person,i)=>`<button type="button" data-person="${i}"><strong>${esc(person.name)}</strong><span>${person.results.length} phiên · Xem bài làm →</span></button>`).join('')}</div><p class="course-method">Điểm tổng = 85% thành tích + 15% điểm tham gia. Điểm tham gia = lượt hợp lệ / mức lượt cao nhất của các đơn vị × 100. Đơn vị đông người có thể đạt 100 điểm tham gia, nhưng phần này chỉ đóng góp tối đa 15 điểm tổng; không tự động đứng đầu. Mỗi người chỉ tính một bài tốt nhất trong từng phiên.</p>`);
    node.querySelectorAll('[data-person]').forEach(button=>button.onclick=()=>openPerson(unit.people[Number(button.dataset.person)]));
  }
  function openPerson(person) {
    if(!person)return;
    dialog('person',person.name,`<p>${esc(person.unit)}</p>${person.achievement!=null?`<div class="course-detail-metrics course-person-summary"><strong>Điểm toàn khóa ${number(person.achievement)}/100</strong><span>Có bài ${person.covered}/${person.totalSessions} phiên</span><span>Tổng thời gian nộp ${elapsed(person.elapsedMs)}</span></div>`:''}${person.results.map(result=>`<section class="course-person-result"><h3>Phiên ${result.sessionId} · ${number(result.points)}/100</h3><p>Nộp sau ${Math.floor(result.durationSeconds/60)} phút ${result.durationSeconds%60} giây từ lúc mở đợt phiên</p>${result.essay?`<blockquote>${esc(result.essay)}</blockquote>`:`<ol>${(result.answers||[]).map(answer=>`<li>${typeof answer==='object'?`<strong>${esc(answer.choice)}</strong><p>${esc(answer.explanation)}</p>`:esc(answer)}</li>`).join('')}</ol>`}</section>`).join('')}`);
  }
  function speech(data) {
    const s=data?.speech;
    if(!s)return '<section class="panel course-speech"><h3>Số liệu phục vụ bế giảng</h3><p>Đang chờ dữ liệu tổng hợp điểm danh và các phiên.</p></section>';
    if(s.error)return `<section class="panel course-speech"><h3>Số liệu phục vụ bế giảng</h3><p>${esc(s.error)}</p></section>`;
    const rate=value=>value==null?'chưa có tỷ lệ':number(value)+'%';
    const text=`Tổng số đơn vị xã, phường tham dự: ${number(s.totalUnits)}/${number(s.invitedUnits)}; tổng số học viên tham dự so với danh sách đăng ký: ${number(s.totalPeople)}/${number(s.registered)}. Bình quân học viên tham gia trả lời câu hỏi mỗi phiên: ${number(s.averagePeople)}/${number(s.totalPeople)}, đạt tỷ lệ ${rate(s.peopleRate)}; bình quân đơn vị tham gia trả lời câu hỏi mỗi phiên: ${number(s.averageUnits)}/${number(s.totalUnits)}, đạt tỷ lệ ${rate(s.unitsRate)}. Trong số thực tế tham dự, có ${number(s.noAnswerUnits)} đơn vị và ${number(s.noAnswerPeople)} học viên chưa tham gia trả lời câu hỏi ở phiên nào.`;
    const correctness=s.sessions.map(session=>`Phiên ${session.id}: ${number(session.correct)}/${number(session.participants)}, đạt ${rate(session.correctRate)}${session.pending?` (còn ${session.pending} bài chờ chấm)`:''}${session.phase!=='CLOSED'?' (phiên đang mở, số liệu tạm thời)':''}`).join('; ');
    return `<section class="panel course-speech" aria-labelledby="speech-title"><div class="leaderboard-heading"><div><p class="panel-kicker">SỐ LIỆU TỰ CẬP NHẬT</p><h3 id="speech-title">Nội dung phục vụ phát biểu bế giảng</h3></div><button class="presentation-trigger" type="button" data-copy-speech>Sao chép đoạn văn</button></div><div class="speech-paragraph"><p>${esc(text)}</p><p>Tỷ lệ học viên trả lời đúng toàn bộ bài so với số học viên tham gia trả lời từng phiên: ${correctness?esc(correctness)+'.':'Chưa có phiên được tổ chức.'}</p></div><p class="course-method">Tính trên ${s.sessionCount} phiên đã mở hoặc đã chốt. Mỗi học viên tính một lần trong mỗi phiên; bài hợp lệ chưa chấm vẫn tính là tham gia. Học viên tham dự được ghi nhận qua điểm danh hai ngày hoặc có bài hợp lệ. “Đúng toàn bộ bài” là đạt 100% điểm; Phiên 2, 7 xét đủ các ý theo kết quả chấm, Phiên 6 xét lựa chọn Đúng/Sai. Số bài chờ chấm vẫn nằm trong mẫu số tỷ lệ đúng. Danh sách đối soát có ${s.rosterRows} người; mẫu số đăng ký là ${s.registered} theo ban tổ chức chốt.</p>${s.unresolved?`<p class="course-warning">Có ${s.unresolved} nhóm nhận diện chưa phân biệt được; số liệu đang đối soát.</p>`:''}<p class="course-method">Cập nhật: ${esc(new Date(s.updatedAt).toLocaleString('vi-VN'))}. Các số liệu trên tiếp tục thay đổi khi có điểm danh, bài hợp lệ hoặc kết quả chấm mới.</p><span data-copy-status role="status"></span></section>`;
  }
  function render(root,data,options={}) {
    if(current && data && (data.status==='WAITING_RECHOT' || JSON.stringify(current.includedSessions)!==JSON.stringify(data.includedSessions))) {
      Array.from(dialogs.values()).reverse().forEach(node=>{if(node.open)node.close();});
    }
    current=data;
    const label=data?.status==='OFFICIAL'?'Chính thức':data?.status==='WAITING_RECHOT'?'Chờ chốt lại':'Tạm thời';
    root.dataset.kind='course';root.dataset.phase='course';
    const admin=options.adminUrl?`${options.adminUrl}${options.adminUrl.includes('?')?'&':'?'}admin=1&view=course&email=${encodeURIComponent(options.email||'')}`:'';
    root.innerHTML=`<section class="section-head"><div><p class="section-kicker">TỔNG KẾT KHÓA</p><h2>Vinh danh đơn vị và cá nhân xuất sắc</h2></div><span class="phase-pill">${label}</span></section>
      <section class="panel course-intro"><p><strong>Tính trên ${data?.includedSessions?.length||0} phiên</strong>${data?.includedSessions?.length?`: ${data.includedSessions.map(id=>'Phiên '+id).join(', ')}`:''}</p><p><strong>Đơn vị: 85% thành tích + 15% mức tham gia.</strong> Mỗi người–mỗi phiên chỉ tính một bài tốt nhất.</p>${data?.publishedAt?`<p>Công bố: ${esc(new Date(data.publishedAt).toLocaleString('vi-VN'))}</p>`:''}${data?.status==='WAITING_RECHOT'?'<p class="course-warning">Một phiên đã Reset, Mở lại hoặc thay đổi cách tính. Kết quả cũ đã rút khỏi công bố; cần chốt và công bố lại.</p>':''}${data?.unresolved?`<p class="course-warning">${data.unresolved} trường hợp cần đối chiếu. Thứ hạng hiện chưa phải kết quả chính thức.</p>`:''}${data?.choices?.some(choice=>choice.phase==='CLOSED'&&choice.pending)?`<p class="course-warning">Còn phiên chờ chấm: ${data.choices.filter(choice=>choice.phase==='CLOSED'&&choice.pending).map(choice=>'Phiên '+choice.id).join(', ')}.</p>`:''}${data?.error?`<p class="course-warning">${esc(data.error)}</p>`:''}${admin?`<a class="button button-admin" href="${esc(admin)}" target="_blank" rel="noopener">Đối chiếu và công bố tổng kết</a>`:''}</section>
      ${options.loading&&!data?'<div class="loading-panel">Đang tổng hợp đơn vị và cá nhân…</div>':data?.top?.length?`<section class="leaderboard panel top-participants-panel course-leaderboard"><div class="leaderboard-heading"><div><p class="panel-kicker">VINH DANH ĐƠN VỊ</p><h3>Top 5 đơn vị cuối khóa</h3></div><button class="presentation-trigger" data-full type="button">Chiếu Top 5 đơn vị ↗</button></div>${cards(data)}${data.top.length>5?'<p>Có đơn vị đồng hạng tại ngưỡng Top 5.</p>':''}</section>`:'<div class="empty">Chưa có đơn vị đủ điều kiện. Cần phiên đã chốt có kết quả và đơn vị có bài ở ít nhất 80% số phiên được tính.</div>'}
      ${data?.individualTop?.length?`<section class="leaderboard panel top-participants-panel course-leaderboard course-individual-leaderboard"><div class="leaderboard-heading"><div><p class="panel-kicker">VINH DANH CÁ NHÂN</p><h3>Top 5 cá nhân xuất sắc nhất khóa</h3></div><button class="presentation-trigger" data-individual-full type="button">Chiếu Top 5 cá nhân ↗</button></div><p class="course-individual-note">Ưu tiên điểm toàn khóa; đồng điểm xét số phiên tham gia, rồi tổng thời gian nộp. Bấm vào học viên để xem bài làm từng phiên.</p>${individualCards(data)}${data.individualTop.length>5?'<p>Có cá nhân đồng hạng tại ngưỡng Top 5.</p>':''}</section>`:data?.includedSessions?.length?'<section class="panel course-individual-empty"><h3>Top 5 cá nhân xuất sắc nhất khóa</h3><p>Chưa có cá nhân đủ điều kiện: cần có bài ở ít nhất 80% các phiên được tính.</p></section>':''}
      <details class="panel course-method"><summary>Cách tính và các phiên chưa được đưa vào tổng kết</summary><p><strong>Đơn vị:</strong> Điểm thành tích là trung bình điểm từng phiên trên thang 100; phiên không có bài của đơn vị tính 0. Điểm tham gia = lượt người–phiên hợp lệ của đơn vị / số lượt cao nhất trong các đơn vị × 100; không dùng danh sách đăng ký. Thành tích đóng góp tối đa 85 điểm, tham gia đóng góp tối đa 15 điểm.</p><p><strong>Cá nhân:</strong> Điểm toàn khóa là trung bình điểm bài tốt nhất của mỗi phiên trên cùng tập phiên được tính; phiên thiếu bài tính 0. Cần tham gia ít nhất 80% số phiên. Đồng điểm ưu tiên số phiên có bài nhiều hơn, rồi tổng thời gian nộp thấp hơn. Thời gian tính từ lúc mở đợt phiên chứa bài gửi; không tính các khoảng phiên đóng. Phiên 6 dùng điểm lựa chọn Đúng/Sai.</p>${data?.choices?`<ul>${data.choices.filter(choice=>!data.includedSessions.includes(choice.id)).map(choice=>`<li>Phiên ${choice.id}: ${choice.phase!=='CLOSED'?'chưa chốt':!choice.count?'chưa có bài hợp lệ':choice.pending?'chờ chấm đủ':'không được chọn khi công bố'}</li>`).join('')}</ul>`:''}</details>`;
    root.innerHTML+=speech(data);
    const copy=root.querySelector('[data-copy-speech]');
    if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(root.querySelector('.speech-paragraph').innerText);root.querySelector('[data-copy-status]').textContent='Đã sao chép đoạn văn.';}catch(_){root.querySelector('[data-copy-status]').textContent='Hãy chọn đoạn văn để sao chép.';}};
    root.querySelectorAll('[data-unit]').forEach(button=>button.onclick=()=>openUnit(Number(button.dataset.unit)));
    root.querySelectorAll('[data-individual]').forEach(button=>button.onclick=()=>openPerson(data.individualTop[Number(button.dataset.individual)]));
    const full=root.querySelector('[data-full]');if(full)full.onclick=()=>dialog('full',`Top 5 đơn vị · ${label}`,`<p class="leaderboard-presentation-note">Tính trên ${data.includedSessions.length} phiên</p>${cards(data)}`,true);
    const individualFull=root.querySelector('[data-individual-full]');if(individualFull)individualFull.onclick=()=>dialog('individual-full',`Top 5 cá nhân · ${label}`,`<p class="leaderboard-presentation-note">${data.includedSessions.length} phiên · Xếp theo điểm, số phiên và thời gian nộp</p>${individualCards(data)}`,true);
  }
  function demo() {
    const result=id=>({sessionId:id,points:100,durationSeconds:120,answers:['3,5,1,6,4,11,9,8,10,13,2,12,7']});
    return {version:1,status:'TEMPORARY',rosterConfirmed:true,includedSessions:[1,2,3,4,5],choices:[],unresolved:0,
      top:Array.from({length:5},(_,i)=>({rank:i+1,unit:['Phường Minh họa A','Xã Minh họa B','Phường Minh họa C','Xã Minh họa D','Xã Minh họa E'][i],total:(90-i*4)*.85+(96-i*4)*.15,achievement:90-i*4,participation:96-i*4,covered:5,totalSessions:5,uniqueParticipants:4,participationMax:19,accepted:19-i,sessions:[1,2,3,4,5].map(id=>({id,participants:4,average:90-i*4})),people:[{id:'demo',name:'Học viên minh họa',unit:'Đơn vị minh họa',results:[result(1)]}]})),
      individualTop:Array.from({length:5},(_,i)=>({personId:'demo-'+i,rank:i+1,name:['Nguyễn Minh Anh','Trần Hoài Nam','Lê Thu Hà','Võ Thanh Bình','Phạm Hồng Vân'][i],unit:'Đơn vị minh họa '+String.fromCharCode(65+i),achievement:98-i*3,covered:5,totalSessions:5,elapsedMs:(630+i*30)*1000,eligible:true,results:[1,2,3,4,5].map(result)}))};
  }
  window.GiaLaiCourse={render,demo};
})();
